name: Construir App Sismica

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar tu código
    - name: Chequear código
      uses: actions/checkout@v4

    # 2. Instalar Python 3.11
    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Instalar Flutter 3.24.5 (Compatible con Flet 0.25.2)
    - name: Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        cache: true

    # 4. Instalar dependencias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Forzamos flet por seguridad
        pip install flet==0.25.2

    # --- PASO NUEVO Y CRUCIAL ---
    # Como tu archivo se llama VBasal.py, lo renombramos a main.py
    # para que Android sepa que ese es el inicio de la app.
    - name: Configurar archivo de inicio
      run: |
        mv VBasal.py main.py

    # 5. Generar el APK
    - name: Construir APK
      run: |
        flet build apk --verbose

    # 6. Subir el APK generado
    - name: Subir el APK generado
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/apk/app-release.apk
